services:
  traefik:
    image: traefik:v3.5.0-rc1
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  deeplinks-help-server:
    build:
      context: ../
      dockerfile: src/backend/Deeplinks.Help.Api/Dockerfile
      target: final
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.deeplinks-help-server.rule=Host(`deeplinks.help`)"
      - "traefik.http.routers.deeplinks-help-server.entrypoints=web"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  deeplinks-help-examples-server:
    build:
      context: ../
      dockerfile: src/backend/Deeplinks.Help.Examples/Dockerfile
      target: final
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.deeplinks-help-examples-server.rule=HostRegexp(`{subdomain:[a-z]+}.deeplinks.help`)"
      - "traefik.http.routers.deeplinks-help-examples-server.entrypoints=web"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
